# action.yml
name: "Post Slack Message"
description: "Post build result message to slack channel"
inputs:
  title:
    description: "Message title"
    required: true
  env:
    description: "Environment"
    required: true
  version:
    description: "Version"
    required: true
  link:
    description: "Link"
    required: true
  webhookUrl:
    description: "webhook url"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
